# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-24 16:55
from __future__ import unicode_literals

import HisaabApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField()),
                ('expense_amount', models.IntegerField(blank=True, null=True)),
                ('payment_amount', models.IntegerField(blank=True, null=True)),
                ('category', models.CharField(blank=True, choices=[(b'TRAVEL', b'Travel Expense'), (b'GROCERIES', b'Groceries'), (b'VEGETABLES', b'Vegetables'), (b'HOUSEHOLD', b'HouseholdItems'), (b'EGG', b'Egg'), (b'MILK', b'Milk & Bread'), (b'TECH EXPENCE', b'Tech Expenses'), (b'OTHER', b'Other')], max_length=25, null=True)),
                ('is_personal_expense', models.BooleanField(default=False)),
                ('is_facility_expense', models.BooleanField(default=False)),
                ('is_pay_forward', models.BooleanField(default=False)),
                ('is_payment_to_ng', models.BooleanField(default=False)),
                ('bank_screenshot', models.ImageField(blank=True, null=True, upload_to=b'bank_screenshot/%Y/%m/%d')),
                ('fellow_payment_screenshot', models.ImageField(blank=True, null=True, upload_to=HisaabApp.models.fellowscreenshot)),
                ('bill_image', models.ImageField(blank=True, null=True, upload_to=b'billimage/%Y/%m/%d')),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_expenses_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MoneyRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(blank=True, max_length=20, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=20, null=True)),
                ('is_money_request', models.BooleanField(default=False)),
                ('is_utility_request', models.BooleanField(default=False)),
                ('account_holder_name', models.CharField(blank=True, max_length=20, null=True)),
                ('type_of_bill', models.CharField(blank=True, choices=[(1, b'Internet'), (2, b'Electricity'), (3, b'WaterBill'), (4, b'Houserent')], max_length=50, null=True)),
                ('bill_image', models.ImageField(blank=True, null=True, upload_to=b'billpayment/%Y/%m/%d')),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_approve', models.BooleanField()),
                ('is_queued', models.BooleanField(default=True)),
                ('reject_text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[(b'ADMIN', b'admin'), (b'FELLOW', b'fellow')], default=b'FELLOW', max_length=20)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.Facility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='approve_or_rejected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.NgUser'),
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.Facility'),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.Facility'),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='fellow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_entry', related_query_name='cash_entry', to='HisaabApp.NgUser'),
        ),
    ]
