# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 05:48
from __future__ import unicode_literals

import HisaabApp.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('expense_amount', models.IntegerField(null=True)),
                ('payment_amount', models.IntegerField(null=True)),
                ('category', models.CharField(choices=[(1, b'Travel Expense'), (2, b'Groceries')], max_length=25, null=True)),
                ('is_personal_expense', models.BooleanField(default=False)),
                ('is_facility_expense', models.BooleanField(default=False)),
                ('is_pay_forward', models.BooleanField(default=False)),
                ('is_payment_to_ng', models.BooleanField(default=False)),
                ('bank_screenshot', models.ImageField(null=True, upload_to=b'bank_screenshot/%Y/%m/%d')),
                ('fellow_payment_screenshot', models.ImageField(null=True, upload_to=HisaabApp.models.fellowscreenshot)),
                ('bill_image', models.ImageField(null=True, upload_to=b'billimage/%Y/%m/%d')),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('student_expenses_limit', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20, null=True)),
                ('ifsc_code', models.CharField(max_length=20, null=True)),
                ('is_money_request', models.BooleanField(default=False)),
                ('is_utility_request', models.BooleanField(default=False)),
                ('account_holder_name', models.CharField(max_length=20, null=True)),
                ('type_of_bill', models.CharField(choices=[(1, b'Internet'), (2, b'Electricity'), (3, b'WaterBill'), (4, b'Houserent')], max_length=50, null=True)),
                ('bill_image', models.ImageField(null=True, upload_to=b'billpayment/%Y/%m/%d')),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_approve', models.BooleanField()),
                ('is_queued', models.BooleanField(default=True)),
                ('reject_text', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_fellow', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.Facility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='moneytransferrequest',
            name='approve_or_rejected_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.NgUser'),
        ),
        migrations.AddField(
            model_name='moneytransferrequest',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.Facility'),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='facility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.Facility'),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='fellow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_entry', related_query_name='cash_entry', to='HisaabApp.NgUser'),
        ),
    ]
