# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 10:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddExpense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_facility_level', models.BooleanField()),
                ('description', models.TextField()),
                ('amount', models.CharField(max_length=5)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('category', models.CharField(choices=[(1, 'Travel Expense'), (2, 'Groceries')], max_length=30)),
                ('expense_photo', models.ImageField(upload_to='expenses/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('student_expenses_limit', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyTransferRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=20)),
                ('confirm_account_number', models.CharField(max_length=20)),
                ('ifsc_code', models.CharField(max_length=20)),
                ('account_holder_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='NgUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.Facility')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RecordPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=5)),
                ('created_date', models.DateField(auto_now_add=True)),
                ('bank_screenshot', models.ImageField(upload_to='bank_screenshot/%Y/%m/%d')),
            ],
        ),
        migrations.CreateModel(
            name='RequestDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('description', models.TextField()),
                ('created_date', models.DateField(auto_now_add=True)),
                ('is_approve', models.BooleanField()),
                ('reject_text', models.TextField(null=True)),
                ('approve_or_rejected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.NgUser')),
            ],
        ),
        migrations.CreateModel(
            name='UtilityBillRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_of_bill', models.CharField(choices=[(1, 'Internet'), (2, 'Electricity'), (3, 'WaterBill'), (4, 'Houserent')], max_length=50)),
                ('bill_image', models.ImageField(upload_to='billpayment/%Y/%m/%d')),
                ('request_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_detail', to='HisaabApp.RequestDetail')),
            ],
        ),
        migrations.AddField(
            model_name='recordpayment',
            name='bill_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.UtilityBillRequest'),
        ),
        migrations.AddField(
            model_name='recordpayment',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.Facility'),
        ),
        migrations.AddField(
            model_name='recordpayment',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments_forward', to='HisaabApp.NgUser'),
        ),
        migrations.AddField(
            model_name='recordpayment',
            name='paid_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_recieved', to='HisaabApp.NgUser'),
        ),
        migrations.AddField(
            model_name='recordpayment',
            name='transfer_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.MoneyTransferRequest'),
        ),
        migrations.AddField(
            model_name='moneytransferrequest',
            name='request_details',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='request_details', to='HisaabApp.RequestDetail'),
        ),
        migrations.AddField(
            model_name='moneytransferrequest',
            name='transfer_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.NgUser'),
        ),
        migrations.AddField(
            model_name='addexpense',
            name='expense_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.NgUser'),
        ),
        migrations.AddField(
            model_name='addexpense',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.Facility'),
        ),
    ]
