# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 05:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneytransferrequest',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
