# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-22 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguser',
            name='user_type',
            field=models.CharField(choices=[(b'ADMIN', b'admin'), (b'SUPER_ADMIN', b'super_admin'), (b'FELLOW', b'fellow')], default=b'FELLOW', max_length=11),
        ),
    ]
