# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-23 10:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordpayment',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='total_payments_forward', to='HisaabApp.NgUser'),
        ),
        migrations.AlterField(
            model_name='recordpayment',
            name='paid_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='total_payment_recieved', to='HisaabApp.NgUser'),
        ),
    ]
