# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-04 10:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_query_name='nguser', to=settings.AUTH_USER_MODEL),
        ),
    ]
