# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0002_auto_20180204_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nguser',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.Facility'),
        ),
    ]
