# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 12:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0003_auto_20180306_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyrequest',
            name='approve_or_rejected_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approve_or_rejected_by', to='HisaabApp.NgUser'),
        ),
    ]
