# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 15:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0003_auto_20180327_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('IFSC_code', models.CharField(max_length=40)),
                ('account_holder_name', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='nguser',
            old_name='upi_id',
            new_name='account_id',
        ),
        migrations.AddField(
            model_name='accountdetail',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account_detail', related_query_name='account_detail', to='HisaabApp.NgUser'),
        ),
    ]
