# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 06:04
from __future__ import unicode_literals

import HisaabApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0003_auto_20180204_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='bank_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=b'bank_screenshot/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'billimage/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='category',
            field=models.CharField(blank=True, choices=[(1, b'Travel Expense'), (2, b'Groceries')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='expense_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.Facility'),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='fellow_payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to=HisaabApp.models.fellowscreenshot),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='payment_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moneytransferrequest',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moneytransferrequest',
            name='account_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moneytransferrequest',
            name='bill_image',
            field=models.ImageField(blank=True, null=True, upload_to=b'billpayment/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='moneytransferrequest',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='moneytransferrequest',
            name='reject_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='moneytransferrequest',
            name='type_of_bill',
            field=models.CharField(blank=True, choices=[(1, b'Internet'), (2, b'Electricity'), (3, b'WaterBill'), (4, b'Houserent')], max_length=50, null=True),
        ),
    ]
