# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0003_auto_20180325_0644'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='cash_in_hand_currently',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
