# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-04 16:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0003_auto_20180204_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='nguser',
            name='is_fellow',
        ),
    ]
