# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 05:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0004_auto_20180204_0604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguser',
            name='is_admin',
        ),
        migrations.RemoveField(
            model_name='nguser',
            name='is_fellow',
        ),
        migrations.AddField(
            model_name='nguser',
            name='user_type',
            field=models.CharField(choices=[(b'ADMIN', b'admin'), (b'FELLOW', b'fellow')], default=2, max_length=20),
        ),
    ]
