# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0004_auto_20180328_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nguser',
            name='account_id',
        ),
    ]
