# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 08:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0004_auto_20180125_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordpayment',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_sent', to='HisaabApp.NgUser'),
        ),
    ]
