# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-06 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0005_auto_20180306_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moneyrequest',
            name='type_of_bill',
            field=models.CharField(blank=True, choices=[(b'INTERNET', b'Internet'), (b'ELECTRICITY', b'Electricity'), (b'WATER', b'WaterBill'), (b'HOUSERENT', b'Houserent')], max_length=50, null=True),
        ),
    ]
