# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-25 08:54
from __future__ import unicode_literals

import HisaabApp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0005_auto_20180125_0836'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('entry_type', models.CharField(choices=[(1, b'Payment'), (2, b'Expenses')], max_length=25)),
                ('transaction_amount', models.CharField(max_length=5)),
                ('is_expense_personal', models.BooleanField()),
                ('category', models.CharField(choices=[(1, b'Travel Expense'), (2, b'Groceries')], max_length=25, null=True)),
                ('is_pay_forward', models.BooleanField()),
                ('is_payment_to_ng', models.BooleanField()),
                ('bank_screenshot', models.ImageField(upload_to=b'bank_screenshot/%Y/%m/%d')),
                ('fellow_payment_screenshot', models.ImageField(upload_to=HisaabApp.models.fellowscreenshot)),
                ('bill_image', models.ImageField(upload_to=b'billimage/%Y/%m/%d')),
                ('fellow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_entry', related_query_name='cash_entry', to='HisaabApp.NgUser')),
            ],
        ),
        migrations.RemoveField(
            model_name='addexpense',
            name='expense_by',
        ),
        migrations.RemoveField(
            model_name='addexpense',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='recordpayment',
            name='bill_request',
        ),
        migrations.RemoveField(
            model_name='recordpayment',
            name='facility',
        ),
        migrations.RemoveField(
            model_name='recordpayment',
            name='paid_by',
        ),
        migrations.RemoveField(
            model_name='recordpayment',
            name='paid_to',
        ),
        migrations.RemoveField(
            model_name='recordpayment',
            name='transfer_request',
        ),
        migrations.DeleteModel(
            name='AddExpense',
        ),
        migrations.DeleteModel(
            name='RecordPayment',
        ),
    ]
