# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0005_auto_20180205_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='category',
            field=models.CharField(blank=True, choices=[(b'tra..', b'Travel Expense'), (b'gro..', b'Groceries'), (b'veg..', b'Vegetables')], max_length=25, null=True),
        ),
    ]
