# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.Category'),
        ),
    ]
