# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-28 15:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0005_remove_nguser_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nguser',
            name='has_account_id',
            field=models.BooleanField(default=False),
        ),
    ]
