# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-02-09 05:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0005_auto_20180209_1030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoneyTransferRequest',
            new_name='MoneyRequest',
        ),
    ]
