# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-27 17:36
from __future__ import unicode_literals

import HisaabApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0006_auto_20180125_0854'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashentry',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cashentry',
            name='is_facility_expense',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='bank_screenshot',
            field=models.ImageField(null=True, upload_to=b'bank_screenshot/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='bill_image',
            field=models.ImageField(null=True, upload_to=b'billimage/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='fellow_payment_screenshot',
            field=models.ImageField(null=True, upload_to=HisaabApp.models.fellowscreenshot),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='is_expense_personal',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='is_pay_forward',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='is_payment_to_ng',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='transaction_amount',
            field=models.IntegerField(),
        ),
    ]
