# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-27 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0006_auto_20180125_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='transaction_amount',
            field=models.IntegerField(),
        ),
    ]
