# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-13 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0006_auto_20180306_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyrequest',
            name='nguser',
        ),
        migrations.AddField(
            model_name='facility',
            name='cash_in_hand',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='money_received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_received_by', to='HisaabApp.NgUser'),
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='money_requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='money_requested_by', to='HisaabApp.NgUser'),
        ),
        migrations.AddField(
            model_name='moneyrequest',
            name='reason_for_reject',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cashentry',
            name='created_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='nguser',
            name='user_type',
            field=models.CharField(choices=[(b'ADMIN', b'admin'), (b'FELLOW', b'fellow')], default=b'FELLOW', max_length=6),
        ),
    ]
