# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-31 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0007_remove_accountdetail_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneyrequest',
            name='account_detail',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='HisaabApp.AccountDetail'),
        ),
    ]
