# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-04-06 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0008_moneyrequest_account_detail'),
        ('HisaabApp', '0006_auto_20180328_1551'),
    ]

    operations = [
    ]
