# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-05-04 07:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0009_merge_20180406_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moneyrequest',
            name='money_received_by',
        ),
    ]
