# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-05 13:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HisaabApp', '0004_auto_20180204_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashentry',
            name='created_date',
            field=models.DateField(),
        ),
    ]
